In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from datetime import datetime
import os
import time
import APTdataloadaer as apt

In [5]:
## 경로설정
path = 'C:/Users/sdjhs/git/dataset/DL'

## 날짜 범위 설정
now_month = datetime.now().strftime('%Y-%m')
date_range = pd.date_range(start='2006-01', end=now_month, freq='MS').strftime('%Y%m').tolist()

## 데이터로더 객체 생성
authKey = apt.authKey
dataloader = apt.AptTradingDataloader(authKey)
## 시군구코드 가져오기
sigungu_cd = list(apt.sigungu_cd.values())

In [ ]:
## date_range.index('201802')

In [6]:
for _sigungu in sigungu_cd[2:]:
    print(f"시군구코드: {_sigungu} 데이터 수집 시작")
    for _date in date_range[:]:
        raw = dataloader.get_apt_trading_raw(_sigungu, _date)
        dataset, df = dataloader.preproc_apt_trading(raw)

        dir_path = os.path.join(f"{path}/trading", _sigungu)
        if not os.path.exists(dir_path):
            os.makedirs(dir_path)

        df.to_csv(os.path.join(dir_path, f'{_date}.csv'), index=False, encoding='utf-8-sig')

        detail_path = os.path.join(f"{path}/trading_detail", _sigungu)
        if not os.path.exists(detail_path):
            os.makedirs(detail_path)

        dataset.to_csv(os.path.join(detail_path, f'{_date}.csv'), index=False, encoding='utf-8-sig')

        time.sleep(3)

시군구코드: 11140 데이터 수집 시작

In [32]:
dir_path

'C:/Users/sdjhs/git/dataset\\11110'

In [26]:


# Create directory if it doesn't exist
for code in sigungu_cd:

,거래년도,거래월,거래일자,법정동시군구코드,법정동읍면동코드,단지일련번호,단지명,전용면적제곱미터,층수,건축년도,거래구분명,거래금액,해제여부
0,2006,1,28,11110,18700,11110-90,현대,114.9,10,2000,None,"52,000",None
1,2006,1,28,11110,17400,11110-37,창신쌍용1,54.7,9,1992,None,"15,950",None
2,2006,1,24,11110,18700,11110-90,현대,60,3,2000,None,"24,000",None
3,2006,1,23,11110,17400,11110-91,창신쌍용2,79.87,12,1993,None,"19,200",None
4,2006,1,20,11110,17400,11110-91,창신쌍용2,106.62,7,1993,None,"28,000",None
5,2006,1,19,11110,17400,11110-91,창신쌍용2,64.66,11,1993,None,"16,500",None
6,2006,1,24,11110,18300,11110-77,일성빌라트,59.82,1,1996,None,"17,500",None
7,2006,1,27,11110,18300,11110-77,일성빌라트,84.99,1,1996,None,"27,000",None
8,2006,1,31,11110,18300,11110-77,일성빌라트,84.99,4,1996,None,"33,500",None
9,2006,1,27,11110,18700,11110-90,현대,114.9,9,2000,None,"56,500",None
10,2006,1,9,11110,13300,11110-16,운현신화타워,57.18,12,1998,None,"15,741",None
11,2006,1,10,11110,13300,11110-16,운현신화타워,84.26,6,1998,None,"23,198",None
12,2006,1,20,11110,13300,11110-16,운현신화타워,78.23,15,1998,None,"21,535",None
13,2006,1,17,11110,18700,11110-90,현대,84.92,9,2000,None,"41,500",None
14,2006,1,18,11110,18700,11110-90,현대,60,13,2000,None,"26,700",None
15,2006,1,17,11110,11700,11110-13,세종,93.4,6,1983,None,"29,500",None
16,2006,1,16,11110,18600,11110-86,대아파크빌,59.22,9,1998,None,"16,000",None
17,2006,1,11,11110,17100,11110-26,명륜동주상복합아남아파트,47.43,6,1999,None,"21,500",None
18,2006,1,4,11110,18700,11110-90,현대,84.92,20,2000,None,"42,500",None
19,2006,1,19,11110,17100,11110-26,명륜동주상복합아남아파트,44.37,8,1999,None,"20,000",None
20,2006,1,11,11110,17400,11110-37,창신쌍용1,54.7,8,1992,None,"16,800",None
21,2006,1,16,11110,18600,11110-86,대아파크빌,59.22,13,1998,None,"16,500",None
22,2006,1,12,11110,13300,11110-16,운현신화타워,84.26,14,1998,None,"23,198",None
23,2006,1,3,11110,17500,11110-131,하림빌라트,47.63,4,1998,None,"10,500",None

In [9]:
sigungu_cd

['11110',
 '11140',
 '11170',
 '11200',
 '11215',
 '11230',
 '11260',
 '11290',
 '11305',
 '11320',
 '11350',
 '11380',
 '11410',
 '11440',
 '11470',
 '11500',
 '11530',
 '11545',
 '11560',
 '11590',
 '11620',
 '11650',
 '11680',
 '11710',
 '11740']